name: publish package

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch: {}
permissions:
  contents: read

jobs:
  test:
    name: release npm package
    runs-on: echoja-remark-custom-container-linux
    strategy:
      matrix:
        node-version: [ 18, 20 ]
    steps:
      - uses: actions/checkout@v7
      - name: setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - name: test
        run: npm run test
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    timeout-minutes: 20
